name: mandarin_dictant
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  video_player: ^2.4.10
  json_annotation: ^4.7.0
  flutter_bloc: ^8.1.1
  file_picker: ^4.0.0
  archive: ^3.3.6
  provider: ^6.0.0
  isolated_worker: ^0.1.1
  js: ^0.6.4
  file_picker_cross: ^4.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  json_serializable: ^6.5.4
  build_runner: ^2.3.3

flutter:
  uses-material-design: true
  assets:
    - content/Vws4DE7UvtM/

platforms:
  android:
  web:
